console.log('Loading counter data...');

const COUNTER_DATA = {
    'Abrams': {
        'Rebutal': 'great',
        'Antiheal': 'great',
        'Reactive Barrier': 'great',
        'Slowing Hex': 'great',
        'Debuff Remover': 'okay',
        'Counter Spell': 'okay',
        'Knockdown': 'bad',
        'Divine Barrier': 'okay',
        'Disarming Hex/Firerate Slows': 'okay',
        'Rescue Beam': 'okay',
        'Spellbreaker': 'okay',
        'Plated Armor': 'bad',
        'Warpstone': 'great',
        'Silence Wave': 'okay',
        'Spirit Shielding': 'okay',
        'Resto Locket': 'okay',
        'Key Ability': 'Charge',
        'Misc Counters': '',
        'Tech': 'Spacing, Verticality, Parrying off charge pre T2, Don\'t focus'
    },
    'Bebop': {
        'Rebutal': 'okay',
        'Antiheal': 'bad',
        'Reactive Barrier': 'great',
        'Slowing Hex': 'bad',
        'Debuff Remover': 'great',
        'Counter Spell': 'great',
        'Knockdown': 'great',
        'Divine Barrier': 'great',
        'Disarming Hex/Firerate Slows': 'great, Gun build only',
        'Rescue Beam': 'okay',
        'Spellbreaker': 'great, Spirit build only',
        'Plated Armor': 'okay',
        'Warpstone': 'okay',
        'Silence Wave': 'okay',
        'Spirit Shielding': 'okay',
        'Resto Locket': 'great',
        'Key Ability': 'Hook',
        'Misc Counters': '',
        'Tech': 'Watch for hook, Meleeing out of uppercut'
    },
    'Billy': {
        'Rebutal': 'great',
        'Antiheal': 'great',
        'Reactive Barrier': 'okay',
        'Slowing Hex': 'okay',
        'Debuff Remover': 'okay',
        'Counter Spell': 'great',
        'Knockdown': 'bad',
        'Divine Barrier': 'great',
        'Disarming Hex/Firerate Slows': 'great',
        'Rescue Beam': 'great',
        'Spellbreaker': 'bad',
        'Plated Armor': 'okay',
        'Warpstone': 'great',
        'Silence Wave': 'okay',
        'Spirit Shielding': 'okay',
        'Resto Locket': 'okay',
        'Key Ability': 'Dash',
        'Misc Counters': '',
        'Tech': 'Break line of sight'
    },
    'Calico': {
        'Rebutal': 'great',
        'Antiheal': 'great',
        'Reactive Barrier': 'bad',
        'Slowing Hex': 'great',
        'Debuff Remover': 'bad',
        'Counter Spell': 'great',
        'Knockdown': 'okay',
        'Divine Barrier': 'great',
        'Disarming Hex/Firerate Slows': 'bad',
        'Rescue Beam': 'okay',
        'Spellbreaker': 'great',
        'Plated Armor': 'bad',
        'Warpstone': 'okay',
        'Silence Wave': 'great',
        'Spirit Shielding': 'great',
        'Resto Locket': 'okay',
        'Key Ability': 'Slash',
        'Misc Counters': '',
        'Tech': 'Shove Wave, She\'s way weaker without her ult'
    },
    'Doorman': {
        'Rebutal': 'okay',
        'Antiheal': 'bad',
        'Reactive Barrier': 'great',
        'Slowing Hex': 'bad',
        'Debuff Remover': 'great',
        'Counter Spell': 'great',
        'Knockdown': 'okay',
        'Divine Barrier': 'okay',
        'Disarming Hex/Firerate Slows': 'okay',
        'Rescue Beam': 'okay',
        'Spellbreaker': 'great',
        'Plated Armor': 'bad',
        'Warpstone': 'okay',
        'Silence Wave': 'okay',
        'Spirit Shielding': 'great',
        'Resto Locket': 'great',
        'Key Ability': 'Cart',
        'Misc Counters': '',
        'Tech': 'Space/Jump cart, CC out of ult'
    },
    'Drifter': {
        'Rebutal': 'okay',
        'Antiheal': 'okay',
        'Reactive Barrier': 'bad',
        'Slowing Hex': 'bad',
        'Debuff Remover': 'great',
        'Counter Spell': 'okay',
        'Knockdown': 'okay',
        'Divine Barrier': 'great',
        'Disarming Hex/Firerate Slows': 'great',
        'Rescue Beam': 'great',
        'Spellbreaker': 'bad',
        'Plated Armor': 'great',
        'Warpstone': 'great',
        'Silence Wave': 'okay',
        'Spirit Shielding': 'okay',
        'Resto Locket': 'great',
        'Key Ability': 'Mark',
        'Misc Counters': '',
        'Tech': 'Space 1, Use Mic'
    },
    'Dynamo': {
        'Rebutal': 'okay',
        'Antiheal': 'okay',
        'Reactive Barrier': 'okay',
        'Slowing Hex': 'great',
        'Debuff Remover': 'okay',
        'Counter Spell': 'okay',
        'Knockdown': 'great',
        'Divine Barrier': 'okay',
        'Disarming Hex/Firerate Slows': 'bad',
        'Rescue Beam': 'great',
        'Spellbreaker': 'great, Kick build only',
        'Plated Armor': 'bad',
        'Warpstone': 'great',
        'Silence Wave': 'great',
        'Spirit Shielding': 'great',
        'Resto Locket': 'okay',
        'Key Ability': 'Entanglement',
        'Misc Counters': '',
        'Tech': 'Space ult, Jump kicks'
    },
    'Grey Talon': {
        'Rebutal': 'okay',
        'Antiheal': 'bad',
        'Reactive Barrier': 'okay',
        'Slowing Hex': 'okay',
        'Debuff Remover': 'bad',
        'Counter Spell': 'great',
        'Knockdown': 'great',
        'Divine Barrier': 'okay',
        'Disarming Hex/Firerate Slows': 'bad',
        'Rescue Beam': 'okay',
        'Spellbreaker': 'great',
        'Plated Armor': 'bad',
        'Warpstone': 'okay',
        'Silence Wave': 'okay',
        'Spirit Shielding': 'great',
        'Resto Locket': 'okay',
        'Key Ability': 'Flight',
        'Misc Counters': '',
        'Tech': 'Wait out/bait traps, don\'t peak when he is in 1'
    },
    'Haze': {
        'Rebutal': 'okay',
        'Antiheal': 'okay',
        'Reactive Barrier': 'great',
        'Slowing Hex': 'bad',
        'Debuff Remover': 'great',
        'Counter Spell': 'okay',
        'Knockdown': 'okay',
        'Divine Barrier': 'great',
        'Disarming Hex/Firerate Slows': 'great',
        'Rescue Beam': 'great',
        'Spellbreaker': 'bad',
        'Plated Armor': 'great',
        'Warpstone': 'great',
        'Silence Wave': 'great',
        'Spirit Shielding': 'okay',
        'Resto Locket': 'great',
        'Key Ability': 'Knife',
        'Misc Counters': '',
        'Tech': 'Play around corners, Location awareness, Let fixation reset'
    },
    'Holiday': {
        'Rebutal': 'okay',
        'Antiheal': 'bad',
        'Reactive Barrier': 'okay',
        'Slowing Hex': 'great',
        'Debuff Remover': 'great',
        'Counter Spell': 'great',
        'Knockdown': 'great',
        'Divine Barrier': 'okay',
        'Disarming Hex/Firerate Slows': 'okay',
        'Rescue Beam': 'great',
        'Spellbreaker': 'great',
        'Plated Armor': 'okay',
        'Warpstone': 'great',
        'Silence Wave': 'great',
        'Spirit Shielding': 'great',
        'Resto Locket': 'great',
        'Key Ability': 'Crackshot',
        'Misc Counters': '',
        'Tech': 'Parry when she melees barrels'
    },
    'Infernus': {
        'Rebutal': 'okay',
        'Antiheal': 'okay',
        'Reactive Barrier': 'okay',
        'Slowing Hex': 'great',
        'Debuff Remover': 'great',
        'Counter Spell': 'great',
        'Knockdown': 'great',
        'Divine Barrier': 'great',
        'Disarming Hex/Firerate Slows': 'great',
        'Rescue Beam': 'great',
        'Spellbreaker': 'bad',
        'Plated Armor': 'great',
        'Warpstone': 'great',
        'Silence Wave': 'okay',
        'Spirit Shielding': 'great',
        'Resto Locket': 'okay',
        'Key Ability': 'Dash',
        'Misc Counters': '',
        'Tech': 'Don\'t peak with burn, Verticality'
    },
    'Ivy': {
        'Rebutal': 'okay',
        'Antiheal': 'okay',
        'Reactive Barrier': 'okay',
        'Slowing Hex': 'okay',
        'Debuff Remover': 'bad',
        'Counter Spell': 'great',
        'Knockdown': 'great',
        'Divine Barrier': 'okay',
        'Disarming Hex/Firerate Slows': 'great',
        'Rescue Beam': 'okay',
        'Spellbreaker': 'bad',
        'Plated Armor': 'okay',
        'Warpstone': 'okay',
        'Silence Wave': 'great',
        'Spirit Shielding': 'okay',
        'Resto Locket': 'okay',
        'Key Ability': 'Stoneform',
        'Misc Counters': '',
        'Tech': 'Verticality for kudzu, CC out of ult'
    },
    'Kelvin': {
        'Rebutal': 'okay',
        'Antiheal': 'great',
        'Reactive Barrier': 'bad',
        'Slowing Hex': 'bad',
        'Debuff Remover': 'great',
        'Counter Spell': 'okay',
        'Knockdown': 'great',
        'Divine Barrier': 'okay',
        'Disarming Hex/Firerate Slows': 'bad',
        'Rescue Beam': 'okay',
        'Spellbreaker': 'okay',
        'Plated Armor': 'bad',
        'Warpstone': 'okay',
        'Silence Wave': 'okay',
        'Spirit Shielding': 'great',
        'Resto Locket': 'okay',
        'Key Ability': 'Beam',
        'Misc Counters': 'Enduring Speed',
        'Tech': 'Parry in dome, Melee in beam'
    },
    'Lady Geist': {
        'Rebutal': 'okay',
        'Antiheal': 'great',
        'Reactive Barrier': 'bad',
        'Slowing Hex': 'bad',
        'Debuff Remover': 'okay',
        'Counter Spell': 'great',
        'Knockdown': 'bad',
        'Divine Barrier': 'okay',
        'Disarming Hex/Firerate Slows': 'okay',
        'Rescue Beam': 'okay',
        'Spellbreaker': 'great',
        'Plated Armor': 'bad',
        'Warpstone': 'great',
        'Silence Wave': 'great',
        'Spirit Shielding': 'great',
        'Resto Locket': 'great',
        'Key Ability': 'Suck',
        'Misc Counters': '',
        'Tech': 'Space ult, Keep stam for bombs'
    },
    'Lash': {
        'Rebutal': 'okay',
        'Antiheal': 'okay',
        'Reactive Barrier': 'okay',
        'Slowing Hex': 'great',
        'Debuff Remover': 'okay',
        'Counter Spell': 'great',
        'Knockdown': 'great',
        'Divine Barrier': 'okay',
        'Disarming Hex/Firerate Slows': 'bad',
        'Rescue Beam': 'great',
        'Spellbreaker': 'great',
        'Plated Armor': 'bad',
        'Warpstone': 'okay',
        'Silence Wave': 'great',
        'Spirit Shielding': 'great',
        'Resto Locket': 'okay',
        'Key Ability': 'Grapple',
        'Misc Counters': '',
        'Tech': 'Play near a roof, Fight indoors'
    },
    'McGinnis': {
        'Rebutal': 'okay',
        'Antiheal': 'okay',
        'Reactive Barrier': 'okay',
        'Slowing Hex': 'bad',
        'Debuff Remover': 'okay',
        'Counter Spell': 'okay',
        'Knockdown': 'bad',
        'Divine Barrier': 'okay',
        'Disarming Hex/Firerate Slows': 'great, Gun build only',
        'Rescue Beam': 'okay',
        'Spellbreaker': 'bad',
        'Plated Armor': 'okay',
        'Warpstone': 'great',
        'Silence Wave': 'okay',
        'Spirit Shielding': 'okay',
        'Resto Locket': 'okay',
        'Key Ability': 'Wall',
        'Misc Counters': '',
        'Tech': 'Don\'t misposition, Clear turrets'
    },
    'Mina': {
        'Rebutal': 'okay',
        'Antiheal': 'great',
        'Reactive Barrier': 'bad',
        'Slowing Hex': 'great',
        'Debuff Remover': 'great',
        'Counter Spell': 'okay',
        'Knockdown': 'great',
        'Divine Barrier': 'okay',
        'Disarming Hex/Firerate Slows': 'okay',
        'Rescue Beam': 'okay',
        'Spellbreaker': 'okay',
        'Plated Armor': 'okay',
        'Warpstone': 'okay',
        'Silence Wave': 'great',
        'Spirit Shielding': 'great',
        'Resto Locket': 'great',
        'Key Ability': 'Bats',
        'Misc Counters': '',
        'Tech': 'Trade quickly without procing love bites'
    },
    'Mirage': {
        'Rebutal': 'okay',
        'Antiheal': 'okay',
        'Reactive Barrier': 'okay',
        'Slowing Hex': 'great',
        'Debuff Remover': 'great',
        'Counter Spell': 'okay',
        'Knockdown': 'okay',
        'Divine Barrier': 'okay',
        'Disarming Hex/Firerate Slows': 'great',
        'Rescue Beam': 'okay',
        'Spellbreaker': 'okay',
        'Plated Armor': 'okay',
        'Warpstone': 'great',
        'Silence Wave': 'okay',
        'Spirit Shielding': 'okay',
        'Resto Locket': 'great',
        'Key Ability': 'Tornado',
        'Misc Counters': '',
        'Tech': 'Save CC for after tornado or if he trys to ult out'
    },
    'Mo & Krill': {
        'Rebutal': 'okay',
        'Antiheal': 'great',
        'Reactive Barrier': 'okay',
        'Slowing Hex': 'bad',
        'Debuff Remover': 'great',
        'Counter Spell': 'okay',
        'Knockdown': 'great',
        'Divine Barrier': 'great',
        'Disarming Hex/Firerate Slows': 'bad',
        'Rescue Beam': 'great',
        'Spellbreaker': 'bad',
        'Plated Armor': 'bad',
        'Warpstone': 'okay',
        'Silence Wave': 'great',
        'Spirit Shielding': 'great',
        'Resto Locket': 'okay',
        'Key Ability': 'Burrow',
        'Misc Counters': '',
        'Tech': 'Vertically, Spacing'
    },
    'Paige': {
        'Rebutal': 'okay',
        'Antiheal': 'bad',
        'Reactive Barrier': 'great',
        'Slowing Hex': 'okay',
        'Debuff Remover': 'great',
        'Counter Spell': 'great',
        'Knockdown': 'great',
        'Divine Barrier': 'okay',
        'Disarming Hex/Firerate Slows': 'bad',
        'Rescue Beam': 'okay',
        'Spellbreaker': 'bad',
        'Plated Armor': 'bad',
        'Warpstone': 'okay',
        'Silence Wave': 'great',
        'Spirit Shielding': 'great',
        'Resto Locket': 'okay',
        'Key Ability': 'Barrier',
        'Misc Counters': '',
        'Tech': 'Focus her.'
    },
    'Paradox': {
        'Rebutal': 'okay',
        'Antiheal': 'bad',
        'Reactive Barrier': 'great',
        'Slowing Hex': 'okay',
        'Debuff Remover': 'okay',
        'Counter Spell': 'okay',
        'Knockdown': 'okay',
        'Divine Barrier': 'okay',
        'Disarming Hex/Firerate Slows': 'bad',
        'Rescue Beam': 'great',
        'Spellbreaker': 'great',
        'Plated Armor': 'bad',
        'Warpstone': 'great',
        'Silence Wave': 'okay',
        'Spirit Shielding': 'great',
        'Resto Locket': 'okay',
        'Key Ability': 'Wall',
        'Misc Counters': '',
        'Tech': 'Play off audio, Don\'t trade when she has wall up'
    },
    'Pocket': {
        'Rebutal': 'okay',
        'Antiheal': 'okay',
        'Reactive Barrier': 'bad',
        'Slowing Hex': 'great',
        'Debuff Remover': 'okay',
        'Counter Spell': 'great',
        'Knockdown': 'okay',
        'Divine Barrier': 'great',
        'Disarming Hex/Firerate Slows': 'bad',
        'Rescue Beam': 'okay',
        'Spellbreaker': 'great',
        'Plated Armor': 'bad',
        'Warpstone': 'okay',
        'Silence Wave': 'great',
        'Spirit Shielding': 'great',
        'Resto Locket': 'okay',
        'Key Ability': 'Case',
        'Misc Counters': '',
        'Tech': 'Don\'t group late, and punish bad cloaks'
    },
    'Seven': {
        'Rebutal': 'okay',
        'Antiheal': 'okay',
        'Reactive Barrier': 'great',
        'Slowing Hex': 'bad',
        'Debuff Remover': 'great',
        'Counter Spell': 'great',
        'Knockdown': 'great',
        'Divine Barrier': 'okay',
        'Disarming Hex/Firerate Slows': 'great',
        'Rescue Beam': 'okay',
        'Spellbreaker': 'bad',
        'Plated Armor': 'great',
        'Warpstone': 'okay',
        'Silence Wave': 'okay',
        'Spirit Shielding': 'great',
        'Resto Locket': 'okay',
        'Key Ability': 'Power Surge',
        'Misc Counters': '',
        'Tech': 'Go near a wall where you can shoot him but his ult doesn\'t hit you'
    },
    'Shiv': {
        'Rebutal': 'okay',
        'Antiheal': 'great',
        'Reactive Barrier': 'bad',
        'Slowing Hex': 'okay',
        'Debuff Remover': 'great',
        'Counter Spell': 'great',
        'Knockdown': 'okay',
        'Divine Barrier': 'great',
        'Disarming Hex/Firerate Slows': 'okay',
        'Rescue Beam': 'okay',
        'Spellbreaker': 'okay',
        'Plated Armor': 'bad',
        'Warpstone': 'okay',
        'Silence Wave': 'great',
        'Spirit Shielding': 'great',
        'Resto Locket': 'great',
        'Key Ability': 'Dash',
        'Misc Counters': '',
        'Tech': 'Space dash, Pay attention to rage'
    },
    'Sinclair': {
        'Rebutal': 'okay',
        'Antiheal': 'bad',
        'Reactive Barrier': 'great',
        'Slowing Hex': 'great',
        'Debuff Remover': 'great',
        'Counter Spell': 'great',
        'Knockdown': 'okay',
        'Divine Barrier': 'okay',
        'Disarming Hex/Firerate Slows': 'bad',
        'Rescue Beam': 'okay',
        'Spellbreaker': 'great',
        'Plated Armor': 'bad',
        'Warpstone': 'okay',
        'Silence Wave': 'great',
        'Spirit Shielding': 'great',
        'Resto Locket': 'okay',
        'Key Ability': 'Assistant',
        'Misc Counters': '',
        'Tech': 'Jump bolts, Com when he takes your ult'
    },
    'Victor': {
        'Rebutal': 'okay',
        'Antiheal': 'great',
        'Reactive Barrier': 'bad',
        'Slowing Hex': 'okay',
        'Debuff Remover': 'okay',
        'Counter Spell': 'okay',
        'Knockdown': 'bad',
        'Divine Barrier': 'okay',
        'Disarming Hex/Firerate Slows': 'okay',
        'Rescue Beam': 'great',
        'Spellbreaker': 'bad',
        'Plated Armor': 'bad',
        'Warpstone': 'okay',
        'Silence Wave': 'great',
        'Spirit Shielding': 'great',
        'Resto Locket': 'okay',
        'Key Ability': 'Pain Battery',
        'Misc Counters': 'Capacitor',
        'Tech': 'Watch your stam, Watch his ult (eyes at the top) Don\'t focus him'
    },
    'Vindicta': {
        'Rebutal': 'okay',
        'Antiheal': 'bad',
        'Reactive Barrier': 'great',
        'Slowing Hex': 'bad',
        'Debuff Remover': 'great',
        'Counter Spell': 'okay',
        'Knockdown': 'great',
        'Divine Barrier': 'great',
        'Disarming Hex/Firerate Slows': 'okay',
        'Rescue Beam': 'okay',
        'Spellbreaker': 'great',
        'Plated Armor': 'okay, Gun build only',
        'Warpstone': 'okay',
        'Silence Wave': 'okay',
        'Spirit Shielding': 'okay',
        'Resto Locket': 'great',
        'Key Ability': 'Stake',
        'Misc Counters': '',
        'Tech': 'Don\'t ego, reset if you\'re low'
    },
    'Viscous': {
        'Rebutal': 'great',
        'Antiheal': 'okay',
        'Reactive Barrier': 'bad',
        'Slowing Hex': 'bad',
        'Debuff Remover': 'bad',
        'Counter Spell': 'okay',
        'Knockdown': 'okay',
        'Divine Barrier': 'okay',
        'Disarming Hex/Firerate Slows': 'okay',
        'Rescue Beam': 'okay',
        'Spellbreaker': 'okay',
        'Plated Armor': 'bad',
        'Warpstone': 'okay',
        'Silence Wave': 'okay',
        'Spirit Shielding': 'great',
        'Resto Locket': 'okay',
        'Key Ability': 'Cube',
        'Misc Counters': 'Capacitor; Armor Piercing Rounds',
        'Tech': 'Parry Puddle Punches, Jump ult, Height in lane'
    },
    'Vyper': {
        'Rebutal': 'okay',
        'Antiheal': 'okay',
        'Reactive Barrier': 'okay',
        'Slowing Hex': 'great',
        'Debuff Remover': 'great',
        'Counter Spell': 'great',
        'Knockdown': 'great',
        'Divine Barrier': 'great',
        'Disarming Hex/Firerate Slows': 'great',
        'Rescue Beam': 'okay',
        'Spellbreaker': 'okay',
        'Plated Armor': 'great',
        'Warpstone': 'great',
        'Silence Wave': 'okay',
        'Spirit Shielding': 'okay',
        'Resto Locket': 'great',
        'Key Ability': 'Venom',
        'Misc Counters': '',
        'Tech': 'High ground, Slow her down'
    },
    'Warden': {
        'Rebutal': 'okay',
        'Antiheal': 'great',
        'Reactive Barrier': 'okay',
        'Slowing Hex': 'okay',
        'Debuff Remover': 'great',
        'Counter Spell': 'great',
        'Knockdown': 'okay',
        'Divine Barrier': 'great',
        'Disarming Hex/Firerate Slows': 'okay',
        'Rescue Beam': 'great',
        'Spellbreaker': 'bad',
        'Plated Armor': 'bad',
        'Warpstone': 'great',
        'Silence Wave': 'okay',
        'Spirit Shielding': 'okay',
        'Resto Locket': 'great',
        'Key Ability': 'Barrier',
        'Misc Counters': '',
        'Tech': 'CC in ult channel, Espace plan, Stam management'
    },
    'Wraith': {
        'Rebutal': 'okay',
        'Antiheal': 'okay',
        'Reactive Barrier': 'bad',
        'Slowing Hex': 'great',
        'Debuff Remover': 'okay',
        'Counter Spell': 'great',
        'Knockdown': 'okay',
        'Divine Barrier': 'okay',
        'Disarming Hex/Firerate Slows': 'great',
        'Rescue Beam': 'great',
        'Spellbreaker': 'okay',
        'Plated Armor': 'great',
        'Warpstone': 'great',
        'Silence Wave': 'okay',
        'Spirit Shielding': 'okay',
        'Resto Locket': 'okay',
        'Key Ability': 'Cards',
        'Misc Counters': '',
        'Tech': 'Watch cards'
    },
    'Yamato': {
        'Rebutal': 'okay',
        'Antiheal': 'great',
        'Reactive Barrier': 'bad',
        'Slowing Hex': 'bad',
        'Debuff Remover': 'bad',
        'Counter Spell': 'great',
        'Knockdown': 'okay',
        'Divine Barrier': 'great',
        'Disarming Hex/Firerate Slows': 'bad',
        'Rescue Beam': 'great',
        'Spellbreaker': 'okay',
        'Plated Armor': 'bad',
        'Warpstone': 'great',
        'Silence Wave': 'great',
        'Spirit Shielding': 'great',
        'Resto Locket': 'great',
        'Key Ability': 'Crimson Slash',
        'Misc Counters': 'Armor Piercing Rounds',
        'Tech': 'Don\'t ego, Don\'t be afraid to go lots of healing and Monster Rounds to play safe'
    }
};

// Define ability icon mappings for ALL counter items
const ABILITY_ICONS = {
    'Rebutal': 'rebuttal.webp',
    'Antiheal': [
        'healbane.webp',
        'toxic-bullets.webp',
        'decay.webp',
        'crippling-headshot.webp',
        'inhibitor.webp',
        'spirit-burn.webp'
    ],
    'Reactive Barrier': 'reactive-barrier.webp',
    'Slowing Hex': 'slowing-hex.webp',
    'Debuff Remover': 'debuff-remover.webp',
    'Counter Spell': 'counterspell.webp',
    'Knockdown': 'knockdown.webp',
    'Divine Barrier': 'divine-barrier.webp',
    'Disarming Hex/Firerate Slows': [
        'disarming-hex.webp',
        'rusted-barrel.webp',
        'suppressor.webp',
        'hunters-aura.webp',
        'juggernaut.webp'
    ],
    'Rescue Beam': 'rescue-beam.webp',
    'Spellbreaker': 'spellbreaker.webp',
    'Plated Armor': 'plated-armor.webp',
    'Warpstone': 'warpstone.webp',
    'Silence Wave': 'silence-wave.webp',
    'Spirit Shielding': 'spirit-shielding.webp',
    'Resto Locket': 'resto-locket.webp'
};

console.log('Counter data loaded for', Object.keys(COUNTER_DATA).length, 'heroes');
